### PR TITLE
Adding link to demo site

### PR DESCRIPTION
**Pull request by drewkerrigan**

### CODE REVIEW

**Comment by sanmiguel** [comment]
I'd be wary of using the word `demo` - does it not imply some kind of interactive setup? We only have a couple of brief outlines and some gifs...

**Comment by ph07** [comment]
Makes sense, let us change 'demo' to 'preview'

**Comment by drewkerrigan** [comment]
I've made the change from the woods.

**Comment by sanmiguel** [comment]
LGTM! Thanks @drewkerrigan the forest-dweller.

**Pull request merged**
